server {
    listen 9090;
    host 0.0.0.0;
    root ./www;
    
    location /upload {
        methods GET POST DELETE;
        upload_store ./www/upload;
        autoindex on;
    }

    location /static {
        methods GET;
        root ./www/static;
        autoindex off;
    }
}