# Faire premier test avec juste ca pour tester 
#server {
    #listen 1234;
    #root ./www/something; 
	#client_max_body_size 10M;
    #location / {
     #   allow_methods GET POST DELETE;
    #}
#} 
#test final


server {
    listen 1111;
    server_name testingdumain;
    root /var/www/htmllllllll;
    index index.htmllllllll;
    client_max_body_size 777;

    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html; #( internal server error )

    location / {
        allow_methods GET;
        autoindex off;
		upload_store /var/www/uploadssssss;
    }

	location /uploads {
        allow_methods GET POST DELETE;
        upload_store /var/www/uploadssssssssss;
        autoindex on;
        client_max_body_size 666;
    }

	location /something {
        allow_methods GET POST DELETE;
        cgi_info .py /usr/bin/python3;
    	cgi_info .php /usr/bin/php-cgi;
    }
}

server {
    listen 22222;
    server_name testingdumain;
    root /var/wwasegfasdg;
    index bloubloou;
    client_max_body_size 77700;

    error_page 404 /errors/404ds.html;
    error_page 500 /errors/500sdgd.html; #( internal server error )

    location / {
        allow_methods GET DELETE;
        autoindex off;
		upload_store /var/www/uploadssssss;
    }
}

server {
    listen 22222;
    server_name tesegfasdg;
    root /var/wwasegfasdg;
    index bloublosedgfasdgu;
    client_max_body_size 7700700;

    error_page 404 /errors/40sdg4ds.html;
    error_page 500 /errors/500sdgasdsdgd.html; #( internal server error )

    location / {
        allow_methods GET;
        autoindex off;
		upload_store /var/www/uploadssssss;
    }
}