# Faire premier test avec juste ca pour tester 
server {
    listen 8080;
    root ./www; # test pour remove comment

    location / {
        allow_methods GET POST DELETE;
    }
	# test again
} 
#test final