@startuml
!theme blueprint

title Classes

' Interface
interface ISocket {
    +close()
    +bind()
    +getFd()
    +setFd(int fd)
}

' Classe abstraite
abstract class ASocket {
    -sockFd : int
    

    +ASocket()
    +connect()
    +disconnect()
}

' Socket client
class SocketClient {
    -buffer : string - read()
    -clientPort : int - ntohs()

}

' Socket serveur
class SocketServer {
    -address : string - recup de htons ?
    +listen()
    +accept() : SocketClient
}

' Relations
ISocket <|.. ASocket
ASocket <|-- SocketClient
ASocket <|-- SocketServer



' Interface
interface IAutre {
    + pub()
}

' Abstraite
abstract class AAutre {
    - priv : int
    + pub()
}

' Classe 1
class autre1 {
    - priv : int
    + pub()
}

' classe 2
class autre2 {
    - priv : int
    + pub()
}

' Relations
IAutre <|.. AAutre
AAutre <|-- autre1
AAutre <|-- autre2


struct addrinfo {
    +int ai_flags;
    +int ai_family;
    +int ai_socktype;
    +int ai_protocol;
    +socklen_t ai_addrlen;
    +struct sockaddr *ai_addr;
    +char *ai_canonname;
    +struct addrinfo *ai_next;

    - hints.ai_family = AF_INET;      // IPv4
    - hints.ai_socktype = SOCK_STREAM; // TCP
    - hints.ai_flags = AI_PASSIVE;    // pour bind
}

@enduml